[package]
name = "logReportServer"
version = "0.1.0"
authors = ["suker <suker@ncsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
whoami = "0.8.1"
threadpool = "1.8.1"
base64 = "0.12.1"
